#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
Regenerates src/core/tests/cipher_vectors.hpp: block, XTS, digest, HMAC and
PBKDF2 vectors for the VeraCrypt ciphers and PRFs that are not in Python's
standard library, produced by independent implementations: Botan 2
(Serpent, Twofish, Camellia-256, Whirlpool, Streebog-512; Debian package
python3-botan) and gostcrypto (Kuznyechik, pip). Run from the repository root.
"""
import hashlib
import struct
import sys

import botan2
import gostcrypto

OUT = "src/core/tests/cipher_vectors.hpp"


def prng(label, n):
    out = bytearray()
    i = 0
    while len(out) < n:
        out += hashlib.sha256(b"stein-cipher:" + label + i.to_bytes(4, "little")).digest()
        i += 1
    return bytes(out[:n])


class Botan:
    def __init__(self, name):
        self.name = name

    def ecb(self, key, data, encrypt=True):
        c = botan2.BlockCipher(self.name)
        c.set_key(key)
        return bytes(c.encrypt(data) if encrypt else c.decrypt(data))


class Kuz:
    name = "Kuznyechik"

    def ecb(self, key, data, encrypt=True):
        c = gostcrypto.gostcipher.new("kuznechik", bytearray(key), gostcrypto.gostcipher.MODE_ECB)
        return bytes(c.encrypt(bytearray(data)) if encrypt else c.decrypt(bytearray(data)))


def gf_mul(t):
    carry = 0
    out = bytearray(16)
    for i in range(16):
        c = t[i] >> 7
        out[i] = ((t[i] << 1) | carry) & 0xFF
        carry = c
    if carry:
        out[0] ^= 0x87
    return bytes(out)


def xts_encrypt(cipher, key64, unit, data):
    """IEEE 1619 XTS with the little-endian 64-bit data-unit number as tweak (plain64)."""
    k1, k2 = key64[:32], key64[32:]
    t = cipher.ecb(k2, struct.pack("<Q", unit) + b"\0" * 8)
    out = bytearray()
    for off in range(0, len(data), 16):
        x = bytes(a ^ b for a, b in zip(data[off:off + 16], t))
        y = cipher.ecb(k1, x)
        out += bytes(a ^ b for a, b in zip(y, t))
        t = gf_mul(t)
    return bytes(out)


CIPHERS = [("serpent", Botan("Serpent")), ("twofish", Botan("Twofish")), ("camellia", Botan("Camellia-256")), ("kuznyechik", Kuz())]
lines = ["// SPDX-License-Identifier: MIT", "// Generated by tools/fixtures/make_cipher_vectors.py (Botan 2 and gostcrypto as oracles).", "#pragma once",
         "namespace stein::test::vectors::cipher {",
         "struct BlockVector { const char* cipher; const char* key; const char* plain; const char* cipherText; };",
         "inline constexpr BlockVector kBlocks[] = {"]
# Published vectors first, then random ones.
known = {
    "serpent": [("0000000000000000000000000000000000000000000000000000000000000000", "00000000000000000000000000000000")],
    "twofish": [("0000000000000000000000000000000000000000000000000000000000000000", "00000000000000000000000000000000")],
    "camellia": [("0123456789abcdeffedcba98765432100011223344556677 8899aabbccddeeff".replace(" ", ""), "0123456789abcdeffedcba9876543210")],
    "kuznyechik": [("8899aabbccddeeff0011223344556677fedcba98765432100123456789abcdef", "1122334455667700ffeeddccbbaa9988")],
}
for name, impl in CIPHERS:
    for key, pt in known[name]:
        ct = impl.ecb(bytes.fromhex(key), bytes.fromhex(pt))
        lines.append('    {"%s", "%s", "%s", "%s"},' % (name, key, pt, ct.hex()))
    for i in range(6):
        key = prng(("%s-key-%d" % (name, i)).encode(), 32)
        pt = prng(("%s-pt-%d" % (name, i)).encode(), 16)
        ct = impl.ecb(key, pt)
        assert impl.ecb(key, ct, encrypt=False) == pt
        lines.append('    {"%s", "%s", "%s", "%s"},' % (name, key.hex(), pt.hex(), ct.hex()))
lines.append("};")
lines.append("struct XtsVector { const char* cipher; const char* key; unsigned long long sector; const char* plain; const char* cipherText; };")
lines.append("inline constexpr XtsVector kXts[] = {")
for name, impl in CIPHERS:
    for i, unit in enumerate((0, 1, 0x123456789ABCDEF)):
        key = prng(("%s-xts-key-%d" % (name, i)).encode(), 64)
        pt = prng(("%s-xts-pt-%d" % (name, i)).encode(), 512 if i == 0 else 64)
        ct = xts_encrypt(impl, key, unit, pt)
        if name != "kuznyechik":   # cross-check our Python XTS against Botan's XTS mode
            m = botan2.SymmetricCipher("%s/XTS" % impl.name, encrypt=True)
            m.set_key(key)
            m.start(struct.pack("<Q", unit) + b"\0" * 8)
            assert m.finish(pt) == ct, name
        lines.append('    {"%s", "%s", %dull, "%s", "%s"},' % (name, key.hex(), unit, pt.hex(), ct.hex()))
lines.append("};")

HASHES = [("whirlpool", "Whirlpool"), ("streebog512", "Streebog-512")]
messages = [b"", b"abc", b"message digest", b"a" * 63, b"a" * 64, b"a" * 65, b"b" * 127, b"c" * 128, b"d" * 129, prng(b"msg-1000", 1000)]
lines.append("struct HashVector { const char* algorithm; const char* messageHex; const char* digest; };")
lines.append("inline constexpr HashVector kHashes[] = {")
for name, bname in HASHES:
    for m in messages:
        h = botan2.HashFunction(bname)
        h.update(m)
        lines.append('    {"%s", "%s", "%s"},' % (name, m.hex(), h.final().hex()))
lines.append("};")
lines.append("struct MacVector { const char* algorithm; const char* hex; };")
lines.append("inline constexpr MacVector kHmacJefe[] = {   // HMAC(\"Jefe\", \"what do ya want for nothing?\")")
for name, bname in HASHES:
    mac = botan2.MsgAuthCode("HMAC(%s)" % bname)
    mac.set_key(b"Jefe")
    mac.update(b"what do ya want for nothing?")
    lines.append('    {"%s", "%s"},' % (name, mac.final().hex()))
lines.append("};")
lines.append("inline constexpr MacVector kHmacLongKey[] = {   // HMAC(131 x 0xaa, \"Test Using Larger Than Block-Size Key - Hash Key First\")")
for name, bname in HASHES:
    mac = botan2.MsgAuthCode("HMAC(%s)" % bname)
    mac.set_key(b"\xaa" * 131)
    mac.update(b"Test Using Larger Than Block-Size Key - Hash Key First")
    lines.append('    {"%s", "%s"},' % (name, mac.final().hex()))
lines.append("};")
lines.append("inline constexpr MacVector kPbkdf2[] = {   // pbkdf2(\"password\", \"salt\", 2000, 192)")
for name, bname in HASHES:
    _, _, dk = botan2.pbkdf("PBKDF2(%s)" % bname, "password", 192, 2000, b"salt")
    lines.append('    {"%s", "%s"},' % (name, dk.hex()))
_, _, dk = botan2.pbkdf("PBKDF2(SHA-512)", "password", 192, 2000, b"salt")
lines.append('    {"sha512", "%s"},' % dk.hex())
lines.append("};")
# gostcrypto's own Streebog agrees with Botan's?
g = gostcrypto.gosthash.new("streebog512", data=bytearray(b"abc"))
hb = botan2.HashFunction("Streebog-512"); hb.update(b"abc")
assert g.digest() == hb.final(), "Streebog oracles disagree"
lines.append("} // namespace stein::test::vectors::cipher")
open(OUT, "w").write("\n".join(lines) + "\n")
print("wrote", OUT, len(lines), "lines")
