#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
layout_gen: turns a *.layout.toml manifest into a C++ header/source pair.

For every top-level table (a struct) it emits:
  * a `StructSpec` + `FieldSpec[]` table (used by stein::layout::describe),
  * a view class with typed getters over a `std::span<const std::byte>`,
  * static typed setters that mutate a `std::span<std::byte>`,
  * `describe(absOffset)` producing the LayoutTree.

Build-time only; the runtime library never parses manifests.
See doc/design/18-structure-layouts.md for the manifest grammar.
"""
import argparse
import re
import sys
import tomllib
from pathlib import Path

INT_TYPES = {
    "u8": ("U8", 1, "std::uint8_t"), "u16": ("U16", 2, "std::uint16_t"),
    "u32": ("U32", 4, "std::uint32_t"), "u64": ("U64", 8, "std::uint64_t"),
    "i8": ("I8", 1, "std::int8_t"), "i16": ("I16", 2, "std::int16_t"),
    "i32": ("I32", 4, "std::int32_t"), "i64": ("I64", 8, "std::int64_t"),
    "crc32": ("Crc32", 4, "std::uint32_t"), "lba": ("Lba", 8, "std::uint64_t"),
    "bits8": ("Bits", 1, "std::uint8_t"), "bits16": ("Bits", 2, "std::uint16_t"),
    "bits32": ("Bits", 4, "std::uint32_t"), "bits64": ("Bits", 8, "std::uint64_t"),
}
SIZED_TYPES = {"ascii": "Ascii", "utf16le": "Utf16le", "bytes": "Bytes"}
FIXED_TYPES = {"guid": ("Guid", 16), "uuid": ("Uuid", 16), "chs": ("Chs", 3)}


def camel(s: str, upper_first: bool) -> str:
    parts = [p for p in re.split(r"[_\-]+", s) if p]
    out = "".join(p[:1].upper() + p[1:] for p in parts)
    return out if upper_first else out[:1].lower() + out[1:]


def cstr(s) -> str:
    if s is None:
        return "nullptr"
    s = str(s).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{s}"'


def parse_int(v) -> int:
    if isinstance(v, int):
        return v
    return int(str(v), 0)


class Field:
    def __init__(self, raw: dict, struct_endian: str, struct_name: str):
        self.name = raw["name"]
        self.offset = parse_int(raw["offset"])
        t = raw["type"]
        self.doc = raw.get("doc", "")
        self.big_endian = raw.get("endian", struct_endian) == "be"
        self.expect_ascii = None
        self.expect_value = None
        self.min = raw.get("min")
        self.max = raw.get("max")
        self.nonzero = bool(raw.get("nonzero", False))
        self.enums = [(parse_int(k), v) for k, v in raw.get("enum", {}).items()]
        self.bits = [(parse_int(k), v) for k, v in raw.get("bits", {}).items()]
        self.pad = raw.get("pad", "\0")
        if t in INT_TYPES:
            self.kind, self.size, self.cpp = INT_TYPES[t]
            self.category = "int"
            if "expect" in raw:
                self.expect_value = parse_int(raw["expect"])
        elif t in SIZED_TYPES:
            self.kind = SIZED_TYPES[t]
            self.size = parse_int(raw["size"])
            self.category = t
            if "expect" in raw:
                self.expect_ascii = str(raw["expect"])
        elif t in FIXED_TYPES:
            self.kind, self.size = FIXED_TYPES[t]
            self.category = t
        else:
            sys.exit(f"{struct_name}.{self.name}: unknown type '{t}'")
        if "size" in raw and t not in SIZED_TYPES and parse_int(raw["size"]) != self.size:
            sys.exit(f"{struct_name}.{self.name}: size {raw['size']} conflicts with type {t}")
        self.ident = camel(self.name, False)
        self.setter = "set" + camel(self.name, True)


class Struct:
    def __init__(self, name: str, raw: dict):
        self.name = name
        self.cls = camel(name, True)
        self.doc = raw.get("doc", "")
        self.size = parse_int(raw["size"])
        endian = raw.get("endian", "le")
        self.fields = [Field(f, endian, name) for f in raw.get("fields", [])]
        for f in self.fields:
            if f.offset + f.size > self.size:
                sys.exit(f"{name}.{f.name}: {f.offset}+{f.size} exceeds struct size {self.size}")
        # overlapping fields are allowed only when explicitly marked (unions are rare but exist)
        spans = sorted((f.offset, f.offset + f.size, f.name) for f in self.fields)
        for a, b in zip(spans, spans[1:]):
            if a[1] > b[0]:
                sys.exit(f"{name}: fields {a[2]} and {b[2]} overlap")


def gen_header(structs, base: str) -> str:
    g = f"stein_layout_gen_{base}"
    out = [
        "// SPDX-License-Identifier: MIT",
        f"// GENERATED by tools/layout_gen/layout_gen.py from formats/{base}.layout.toml. Do not edit.",
        "#pragma once",
        "",
        '#include "stein/core/guid.hpp"',
        '#include "stein/layout/describe.hpp"',
        '#include "stein/layout/node.hpp"',
        '#include "stein/layout/spec.hpp"',
        "",
        "#include <cstdint>",
        "#include <span>",
        "#include <string>",
        "#include <string_view>",
        "",
        "namespace stein::layout::gen {",
        "",
    ]
    for s in structs:
        out.append(f"// {s.doc}" if s.doc else f"// {s.name}")
        out.append(f"class {s.cls} {{")
        out.append("public:")
        out.append(f"    static constexpr std::uint32_t kSize = {s.size};")
        out.append("    static const StructSpec& spec();")
        out.append("")
        out.append(f"    // View over at least kSize bytes; the caller guarantees the length.")
        out.append(f"    explicit {s.cls}(std::span<const std::byte> bytes) : m_bytes(bytes) {{}}")
        out.append("    std::span<const std::byte> bytes() const { return m_bytes; }")
        out.append("    Node describe(std::uint64_t absOffset) const { return stein::layout::describe(spec(), m_bytes, absOffset); }")
        out.append("")
        out.append("    // Field offsets, for code that addresses pieces directly.")
        for f in s.fields:
            out.append(f"    static constexpr std::uint32_t k{camel(f.name, True)}Offset = {f.offset};")
            out.append(f"    static constexpr std::uint32_t k{camel(f.name, True)}Size = {f.size};")
        out.append("")
        out.append("    // Getters")
        for f in s.fields:
            if f.category == "int":
                out.append(f"    {f.cpp} {f.ident}() const;")
            elif f.category in ("ascii", "utf16le"):
                out.append(f"    std::string {f.ident}() const;")
            elif f.category in ("guid", "uuid"):
                out.append(f"    Uuid {f.ident}() const;")
            elif f.category == "chs":
                out.append(f"    ChsAddress {f.ident}() const;")
            else:
                out.append(f"    std::span<const std::byte> {f.ident}() const;")
        out.append("")
        out.append("    // Setters (mutate a writable copy of the struct's bytes)")
        for f in s.fields:
            if f.category == "int":
                out.append(f"    static void {f.setter}(std::span<std::byte> bytes, {f.cpp} value);")
            elif f.category == "ascii":
                out.append(f"    static void {f.setter}(std::span<std::byte> bytes, std::string_view value);")
            elif f.category == "utf16le":
                out.append(f"    static bool {f.setter}(std::span<std::byte> bytes, std::string_view utf8); // false if truncated")
            elif f.category in ("guid", "uuid"):
                out.append(f"    static void {f.setter}(std::span<std::byte> bytes, const Uuid& value);")
            elif f.category == "chs":
                out.append(f"    static void {f.setter}(std::span<std::byte> bytes, const ChsAddress& value);")
            else:
                out.append(f"    static void {f.setter}(std::span<std::byte> bytes, std::span<const std::byte> value);")
        out.append("")
        out.append("private:")
        out.append("    std::span<const std::byte> m_bytes;")
        out.append("};")
        out.append("")
    out.append("} // namespace stein::layout::gen")
    out.append("")
    return "\n".join(out)


def gen_source(structs, base: str) -> str:
    out = [
        "// SPDX-License-Identifier: MIT",
        f"// GENERATED by tools/layout_gen/layout_gen.py from formats/{base}.layout.toml. Do not edit.",
        f'#include "stein/layout/gen/{base}.hpp"',
        "",
        '#include "stein/core/strings.hpp"',
        "",
        "#include <algorithm>",
        "",
        "namespace stein::layout::gen {",
        "",
        "namespace {",
        "",
    ]
    for s in structs:
        for f in s.fields:
            if f.enums:
                out.append(f"const EnumValue k{s.cls}_{camel(f.name, True)}_Enums[] = {{")
                for v, name in f.enums:
                    out.append(f"    {{{v:#x}ull, {cstr(name)}}},")
                out.append("};")
            if f.bits:
                out.append(f"const BitName k{s.cls}_{camel(f.name, True)}_Bits[] = {{")
                for v, name in f.bits:
                    out.append(f"    {{{v}, {cstr(name)}}},")
                out.append("};")
        out.append(f"const FieldSpec k{s.cls}_Fields[] = {{")
        for f in s.fields:
            enums = f"k{s.cls}_{camel(f.name, True)}_Enums" if f.enums else "nullptr"
            bits = f"k{s.cls}_{camel(f.name, True)}_Bits" if f.bits else "nullptr"
            out.append("    {" + ", ".join([
                cstr(f.name), str(f.offset), str(f.size), f"FieldType::{f.kind}",
                "true" if f.big_endian else "false", cstr(f.doc),
                cstr(f.expect_ascii) if f.expect_ascii is not None else "nullptr",
                "true" if f.expect_value is not None else "false",
                f"{f.expect_value}ull" if f.expect_value is not None else "0",
                "true" if f.min is not None else "false", "true" if f.max is not None else "false",
                f"{parse_int(f.min)}ull" if f.min is not None else "0",
                f"{parse_int(f.max)}ull" if f.max is not None else "0",
                "true" if f.nonzero else "false",
                enums, str(len(f.enums)), bits, str(len(f.bits)),
            ]) + "},")
        out.append("};")
        out.append(f"const StructSpec k{s.cls}_Spec = {{{cstr(s.name)}, {cstr(s.doc)}, {s.size}, k{s.cls}_Fields, {len(s.fields)}}};")
        out.append("")
    out.append("} // namespace")
    out.append("")
    for s in structs:
        out.append(f"const StructSpec& {s.cls}::spec() {{ return k{s.cls}_Spec; }}")
        out.append("")
        for i, f in enumerate(s.fields):
            fs = f"k{s.cls}_Fields[{i}]"
            sub = f"m_bytes.subspan({f.offset}, {f.size})"
            wsub = f"bytes.subspan({f.offset}, {f.size})"
            if f.category == "int":
                out.append(f"{f.cpp} {s.cls}::{f.ident}() const {{ return static_cast<{f.cpp}>(readUnsigned({fs}, m_bytes)); }}")
                out.append(f"void {s.cls}::{f.setter}(std::span<std::byte> bytes, {f.cpp} value) {{ writeUnsigned({fs}, bytes, static_cast<std::uint64_t>(value)); }}")
            elif f.category == "ascii":
                pad = ord(f.pad[0]) if f.pad else 0
                out.append(f"std::string {s.cls}::{f.ident}() const {{ return asciiField({sub}); }}")
                out.append(f"void {s.cls}::{f.setter}(std::span<std::byte> bytes, std::string_view value) {{ setAsciiField({wsub}, value, std::byte{{{pad}}}); }}")
            elif f.category == "utf16le":
                out.append(f"std::string {s.cls}::{f.ident}() const {{ return utf16leToUtf8({sub}); }}")
                out.append(f"bool {s.cls}::{f.setter}(std::span<std::byte> bytes, std::string_view utf8) {{ return utf8ToUtf16le(utf8, {wsub}); }}")
            elif f.category == "guid":
                out.append(f"Uuid {s.cls}::{f.ident}() const {{ return Uuid::fromGptBytes(std::span<const std::byte, 16>({sub})); }}")
                out.append(f"void {s.cls}::{f.setter}(std::span<std::byte> bytes, const Uuid& value) {{ value.toGptBytes(std::span<std::byte, 16>({wsub})); }}")
            elif f.category == "uuid":
                out.append(f"Uuid {s.cls}::{f.ident}() const {{ return Uuid::fromRfcBytes(std::span<const std::byte, 16>({sub})); }}")
                out.append(f"void {s.cls}::{f.setter}(std::span<std::byte> bytes, const Uuid& value) {{ value.toRfcBytes(std::span<std::byte, 16>({wsub})); }}")
            elif f.category == "chs":
                out.append(f"ChsAddress {s.cls}::{f.ident}() const {{ return decodeChs({sub}); }}")
                out.append(f"void {s.cls}::{f.setter}(std::span<std::byte> bytes, const ChsAddress& value) {{ encodeChs({wsub}, value); }}")
            else:
                out.append(f"std::span<const std::byte> {s.cls}::{f.ident}() const {{ return {sub}; }}")
                out.append(f"void {s.cls}::{f.setter}(std::span<std::byte> bytes, std::span<const std::byte> value) {{")
                out.append(f"    auto dst = {wsub};")
                out.append("    std::fill(dst.begin(), dst.end(), std::byte{0});")
                out.append("    std::copy_n(value.begin(), std::min(value.size(), dst.size()), dst.begin());")
                out.append("}")
        out.append("")
    out.append("} // namespace stein::layout::gen")
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("manifest", type=Path)
    ap.add_argument("--hpp", type=Path, required=True)
    ap.add_argument("--cpp", type=Path, required=True)
    args = ap.parse_args()
    try:
        data = tomllib.loads(args.manifest.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as e:
        sys.exit(f"{args.manifest}: TOML error: {e} (note: inline tables must stay on one line)")
    base = args.manifest.name.split(".")[0]
    structs = [Struct(name, raw) for name, raw in data.items() if isinstance(raw, dict)]
    if not structs:
        sys.exit(f"{args.manifest}: no structs")
    args.hpp.parent.mkdir(parents=True, exist_ok=True)
    args.cpp.parent.mkdir(parents=True, exist_ok=True)
    args.hpp.write_text(gen_header(structs, base), encoding="utf-8")
    args.cpp.write_text(gen_source(structs, base), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
